app/port/controller/PackageController.ts, config/plugin.ts, package.json
在 ts 场景下，使用 [egg-typebbox-validate ](https://github.com/xiekw2010/egg-typebox-validate)来替换 egg-validate
=> feat: using egg-typebox-validate for PackageController

app/core/service/PackageManagerService.ts, app/core/service/PackageSyncerService.ts, test/core/service/PackageSyncerService/executeTask.test.ts
closes https://github.com/cnpm/cnpmcore/issues/28
=> 👌 IMPROVE: skip refresh manifests on per version sync

sql/init.sql
sqlMessage: "Duplicate entry '/packages/koa-middlewares/abbreviated_manifests.json' for key 'uk_path'"
sqlState: "23000"
index: 0
sql: "INSERT INTO `dists` (`gmt_create`, `gmt_modified`, `dist_id`, `name`, `path`, `size`, `shasum`, `integrity`) VALUES ('2021-12-18 21:47:14.766', '2021-12-18 21:47:14.766', '61bde662a6f1dd2f7de4173b', 'abbreviated_manifests.json', '/packages/koa-middlewares/abbreviated_manifests.json', 31687, 'db5874f05972871f3b21e356e7ce03f0b73c1802', 'sha512-vwNzCjJK/EI1jeZ4rXWcHpSqdTmK37JTEWQTZXobD/QiPzczQXeJHVee+JDiWnQYbmg8S/NJX979mzouObAP1Q==')"
name: "ER_DUP_ENTRYError"
pid: 143227
=> 🐛 FIX: dists table should not has path unique key

app/port/controller/UserController.ts, test/port/controller/UserController/saveProfile.test.ts, test/port/controller/UserController/showProfile.test.ts
https://github.com/cnpm/cnpmcore/issues/64
=> 📦 NEW: Support profile command

sql/init.sql, test/port/controller/DownloadController/showPackageDownloads.test.ts
```
ER_DATA_TOO_LONG: Data too long for column 'package_id' at row 1
```
=> 🐛 FIX: Download scope too long than package_id

app/common/adapter/binary/NodeBinary.ts, app/port/binary.html, config/binaries.ts, test/common/adapter/binary/NodeBinary.test.ts
log: https://r.cnpmjs.org/-/binary/python/syncs/61ffced0bb8a154e465993a7/log
=> 🐛 FIX: ignore duplicate key filename on python binary

app/common/adapter/binary/ImageminBinary.ts, config/binaries.ts, test/common/adapter/binary/ImageminBinary.test.ts
closes https://github.com/cnpm/mirrors/issues/283
=> 🐛 FIX: mozjpeg-bin should use mozjpeg for npm package name

app/core/service/PackageSyncerService.ts, app/repository/PackageRepository.ts, test/core/service/PackageSyncerService/executeTask.test.ts
Skip database query on exists version to improve speed
=> 👌 IMPROVE: Should check version on abbreviated manifests too

package.json
should use with `"moduleResolution": "NodeNext"`.
=> feat: add type for exports

app/common/adapter/binary/NodePreGypBinary.ts, config/binaries.ts, test/common/adapter/binary/NodePreGypBinary.test.ts
closes https://github.com/cnpm/cnpmcore/pull/258
=> 🐛 FIX: skia-canvas should use NodePreGypBinary

app/schedule/SyncPackageWorker.ts
app.config.cnpmcore.syncPackageWorkerMaxConcurrentTasks may dynamic
modify, should check executingCount in every loop.
=> fix: check executingCount after task is done

app/common/LogUtil.ts, app/common/enum/Hook.ts, app/common/enum/Task.ts, app/core/entity/Hook.ts, app/core/entity/HookEvent.ts, app/core/entity/Task.ts, app/core/event/ChangesStream.ts, app/core/event/index.ts, app/core/service/ChangesStreamService.ts, app/core/service/CreateHookTriggerService.ts, app/core/service/HookTriggerService.ts, app/core/service/PackageManagerService.ts, app/port/controller/HookController.ts, app/port/controller/convertor/HookConvertor.ts, app/repository/HookRepository.ts, app/repository/TaskRepository.ts, app/repository/UserRepository.ts, app/schedule/CreateTriggerHookWorker.ts, app/schedule/TriggerHookWorker.ts, config/config.default.ts, test/core/service/CreateHookTriggerService.test.ts, test/core/service/HookManageService/createHook.test.ts, test/core/service/HookTriggerService.test.ts, test/port/controller/hook/HookController.test.ts, test/repository/TaskRepository.test.ts
Refs:
- https://github.com/cnpm/cnpmcore/issues/282
=> feat: impl trigger Hooks

app/common/enum/Registry.ts, app/core/entity/Registry.ts, app/core/entity/Scope.ts, app/core/service/RegistryManagerService.ts, app/core/service/ScopeManagerService.ts, app/core/util/EntityUtil.ts, app/port/controller/RegistryController.ts, app/port/controller/ScopeController.ts, app/port/middleware/AdminAccess.ts, app/port/typebox.ts, app/repository/RegistryRepository.ts, app/repository/ScopeRepository.ts, app/repository/model/Registry.ts, app/repository/model/Scope.ts, sql/1.11.0.sql, test/core/service/RegistryManagerService/index.test.ts, test/core/service/ScopeManagerService/index.test.ts, test/core/util/EntityUtil.test.ts, test/port/controller/RegistryController/index.test.ts, test/port/controller/ScopeController/index.test.ts, test/repository/RegistryRepository.test.ts, test/repository/ScopeRepository.test.ts
1. 初始化 Registry 和 Scope 模型及接口
2. Registry 和 Scope 为一等公民，单独用接口来处理增啥改查和关联关系信息
3. 仅管理员可作修改，所有人可以进行查询
~~4. Registry 查询 VO 模型内，返回 scopes 信息~~
5. 新增 @Middleware AdminAccess 中间件处理管理员鉴权
=> feat: init registry and scope

app/common/adapter/changesStream/AbstractChangesStream.ts, app/common/adapter/changesStream/CnpmcoreChangesStream.ts, app/common/adapter/changesStream/CnpmjsorgChangesStream.ts, app/common/adapter/changesStream/NpmChangesStream.ts, app/core/entity/Registry.ts, app/core/entity/Task.ts, app/core/service/ChangesStreamService.ts, app/core/service/ScopeManagerService.ts, app/core/util/ChangesStreamTransform.ts, app/port/controller/RegistryController.ts, app/port/controller/ScopeController.ts, app/repository/ScopeRepository.ts, app/repository/model/Registry.ts, test/common/adapter/changesStream/CnpmcoreChangesStream.test.ts, test/common/adapter/changesStream/CnpmjsorgChangesStream.test.ts, test/common/adapter/changesStream/NpmChangesStream.test.ts, test/core/service/ChangesStreamService.test.ts, test/core/service/RegistryManagerService/index.test.ts, test/core/util/ChangesStreamTransform.test.ts, test/repository/TaskRepository.test.ts
> [ref](https://github.com/cnpm/cnpmcore/pull/284) 子任务
1. 新增 changesStream Adapter 层
* getInitalSince 负责返回不通 changesStream 对应初始参数
* fetchChanges 负责获取同步源对应变更数据，统一返回 stream 进行消费
2. 修改 changesStreamService 实现
* prepareRegsitry 负责兼容旧启动参数，初始化 registry 信息
* 修改原有 taskData 更新流程
=> feat: changesStream adapter & needSync() method

app/core/entity/Task.ts, app/core/service/ChangesStreamService.ts, app/core/service/RegistryManagerService.ts, app/repository/model/HistoryTask.ts, app/repository/model/PackageVersionBlock.ts, app/repository/model/Task.ts, test/core/service/ChangesStreamService.test.ts, test/core/service/RegistryManagerService/index.test.ts
1. 修复 registry/sync 初始化时没有传递 registryId 问题
2. 修复 changesStream 获取时，如果没有需要同步的任务会导致 task#since 无法更新
=> fix: changes stream

app/core/service/TaskService.ts, app/repository/util/ModelConvertor.ts, test/repository/TaskRepository.test.ts
* 🧶 ModelConvertor 新增 autoUpdatedAt 参数，taskRepository.saveTask 默认开启。
目前 saveTask 前会先从 db 内查询 entity.id 对应的 model，如果 updatedAt 不一致则更新。
如果单个任务有多个 worker 在执行，会导致 updatedAt 和 entity 不一致，导致 updaptedAt 被错误覆盖。
后续会触发 timeout Retry，放大异常。
=> fix: task updatedAt save

app/core/entity/Task.ts, app/core/service/ChangesStreamService.ts, test/common/adapter/changesStream/CnpmcoreChangesStream.test.ts, test/repository/TaskRepository.test.ts
* 修复 changesStream data 内容不变时， updateAt 字段未更新的问题。
* 修复 executeSync 累积耗时超过 10min 时，会导致 changesStream 状态判断异常。
retryExecuteTimeoutTasks 对于 10min 未更新 updatedAt 的任务，会重新 push 进队列。
changesStream Worker 会重新初始化任务执行，
导致多个 changesStream 并行抢占 updatedAt。
=> fix: changes stream updatedAt

app/core/service/TaskService.ts, test/core/service/TaskService/findExecuteTask.test.ts
taskService.findExecuteTask 添加判断，只处理状态仍为 waiting 状态的 task
=> fix: execute state check

app/common/adapter/changesStream/CnpmjsorgChangesStream.ts, test/common/adapter/changesStream/CnpmjsorgChangesStream.test.ts
* 🐞 修复 cnpmjs.org 类型 changesStream 返回最新 changes 时，计数异常
=> fix: cnpmjsorg changesstream limit

app/core/entity/Task.ts, app/core/service/TaskService.ts, app/repository/TaskRepository.ts, app/repository/util/ModelConvertor.ts, test/core/service/TaskService/findExecuteTask.test.ts, test/repository/TaskRepository.test.ts
If multi instance access queue may return
same task id, update task attemp idempotent
for safe concurrent.
=> fix: findExecuteTask only return waiting task

app/core/service/ChangesStreamService.ts, app/port/controller/AbstractController.ts, app/port/controller/PackageSyncController.ts, app/port/schedule/CheckRecentlyUpdatedPackages.ts, config/config.default.ts, test/core/service/ChangesStreamService.test.ts, test/schedule/CheckRecentlyUpdatedPackages.test.ts
添加`syncMode: exist`的支持，参考：https://github.com/cnpm/cnpmjs.org/blob/master/sync/sync_exist.js 的实现，定时自动同步所有存量的包，默认值为每周日凌晨1点整开始同步
注意事项：建议企业内部使用时，关闭 `enableChangesStream`，同时也关闭 `enableCheckRecentlyUpdated`。手工同步一些常见的包后，再启用 `syncMode: exist`，这样包的数量可控，也能保障包的状态是最新的
=> feat: support sync exist mode

app/core/service/PackageManagerService.ts, app/core/service/PackageSyncerService.ts, test/core/service/PackageSyncerService/executeTask.test.ts
> packageSyncer#executeTask 时，根据 scope 和 data.registryId 更新 pkg.registryId 配置
解决问题:
1. 例如 @cnpm 配置特定 registry，当 @cnpm/a 依赖了 @cnpm/b 时，@cnpm/b 同步任务执行异常
2. 存量 registryId 为 null 的 package 无时机更新 registryId
3. 存量 registryId 为 null ，手动触发 sync 任务时，不支持传入 registryName: default
=> Lazy set registryId when executeTask

app/core/service/ChangesStreamService.ts, sql/1.12.0.sql
fix #343 
之前默认用 changesStreamRegistry 作为默认的 registry 源，导致部分数据丢失。
~~* registryManageService 新增 ensureDefaultRegistry 方法~~
~~* 配置更新时，根据配置进行同步 defaultRegistry 配置~~
* 更新创建默认 registry 字段
* 添加 sql 订正脚本
=> fix: registry host config

app/core/service/PackageManagerService.ts, test/core/service/PackageManagerService/publish.test.ts
目前 db 限制 pkg.description 长度为 10k，cnpmjs.org 为 longtext，可能导致不兼容。
* 长 description 场景，截断字符保存，防止创建 pkg 失败
=> feat: long description

app/core/entity/Task.ts, app/core/service/BinarySyncerService.ts, test/core/service/BinarySyncerService/createTask.test.ts
> syncBinary 目前会通过定时任务单机每天创建，导致多实例冲突
> 其他任务类型均通过事件触发不受影响
* 创建 syncBinary 任务时，手动去重
* 添加 bizId 参数 进行兜底
=> fix: duplicate binary task

app/common/adapter/binary/AbstractBinary.ts, app/common/adapter/binary/ApiBinary.ts, app/common/adapter/binary/ImageminBinary.ts, app/common/adapter/binary/NodePreGypBinary.ts, app/core/service/BinarySyncerService.ts, app/port/controller/BinarySyncController.ts, app/port/schedule/CreateSyncBinaryTask.ts, config/binaries.ts, test/TestUtil.ts, test/common/adapter/binary/ApiBinary.test.ts, test/common/adapter/binary/BucketBinary.test.ts, test/common/adapter/binary/CypressBinary.test.ts, test/common/adapter/binary/ElectronBinary.test.ts, test/common/adapter/binary/GithubBinary.test.ts, test/common/adapter/binary/ImageminBinary.test.ts, test/common/adapter/binary/NodeBinary.test.ts, test/common/adapter/binary/NodePreGypBinary.test.ts, test/common/adapter/binary/NwjsBinary.test.ts, test/common/adapter/binary/PlaywrightBinary.test.ts, test/common/adapter/binary/PuppeteerBinary.test.ts, test/common/adapter/binary/SqlcipherBinary.test.ts, test/port/controller/BinarySyncController/showBinary.test.ts
1. 默认使用 config/binaries 的 binaryName 创建同步任务；
2. config/binaries 中的 category 为组合不同 binary 数据的配置。默认跟 binaryName 保持一致；
3. 当 category 跟 binaryName 不一致时，合并 binaryName 和 category 两个二进制数据信息。
以 canvas 和 node-canvas-prebuilt 为例：
1. 创建同步任务时，分别同步各自的数据；
2. 查询二进制数据时，由于 canvas 中的 category 配置为 node-canvas-prebuilt，这时候会合并 canvas 和 node-canvas-prebuilt 两个 binary（binaryName）的数据并返回。
这个重构删除 mergeCategory 字段，使得配置数据更加精简。
=> refactor: binary sync task use binaryName by default

app/core/service/EventCorkerAdvice.ts, app/core/service/PackageSyncerService.ts, app/port/schedule/SyncPackageWorker.ts, test/core/service/PackageSyncerService/createTask.test.ts, test/core/service/PackageSyncerService/executeTask.test.ts
> syncPackage 同步时，由于任务并发，可能会导致同步过程中 versions 表记录已经创建，pkg.manifests 还没有同步
> 针对这种场景做补偿逻辑，防止 tag 打在一个 pkg.manifests 没有的版本里
* 修改 pkg.manifests 补偿逻辑，兼容有 versions 没 pkg.manifests 的情况
* 添加 eventCork 的 advice，在 syncPackage 任务结束后，再统一触发 changes，依赖 [ref](https://github.com/eggjs/tegg/pull/60)
在同步和被同步的场景，确保 changes 发出时，pkg.manifests 已经更新
统一 ctx 内不同 changes 时序可能影响，不影响重新读取 manifests 一致性
=> Event cork

app/core/service/PackageManagerService.ts, app/core/service/PackageSyncerService.ts, test/core/service/PackageSyncerService/executeTask.test.ts
> 2个同步任务并发执行时，可能出现查询时未写入版本，写入时冲突，导致未正常更新 pkg.manifests
* 识别写入异常场景，由于 version 写入已添加 nfs 和 关联数据事务，可以直接放入 updatedVersions 数组进行 manifests 更新
* dist-tag 添加校验逻辑，对于 dist-tag 的更新，必须确保存量 manifests 或本次同步增量的 versions 包含对应版本，否则跳过
=> Sync save dup

app/core/service/PackageSyncerService.ts, test/core/service/PackageSyncerService/executeTask.test.ts
> https://registry.npmmirror.com/chalk-next 
如果上游 cnpmcore registry block 包时，下游同步时目前会同步失败，导致包无法自动废弃
* 上游包 unblock 时，下游包应当 unpublish 处理，follow upstream 操作
=> feat: unpublish pkg when upstream block

app/common/adapter/binary/NodePreGypBinary.ts, test/common/adapter/binary/NodePreGypBinary.test.ts
> 目前逻辑会解析出 ` https://skia-canvas.s3.us-east-1.amazonaws.com/v0.9.24/linux-arm64-{node_napi_label}.tar.gz`  会导致任务多次失败重试
* 添加 if/else 判断兼容 `{platform}-{arch}-{node_napi_label}` 
* 临时兼容，后续通过变量替换实现
=> fix: binary path

app/common/adapter/binary/AbstractBinary.ts, app/common/adapter/binary/ApiBinary.ts, app/common/adapter/binary/BucketBinary.ts, app/common/adapter/binary/CypressBinary.ts, app/common/adapter/binary/ElectronBinary.ts, app/common/adapter/binary/GithubBinary.ts, app/common/adapter/binary/ImageminBinary.ts, app/common/adapter/binary/NodeBinary.ts, app/common/adapter/binary/NodePreGypBinary.ts, app/common/adapter/binary/NwjsBinary.ts, app/common/adapter/binary/PlaywrightBinary.ts, app/common/adapter/binary/PuppeteerBinary.ts, app/common/adapter/binary/SqlcipherBinary.ts, app/core/service/BinarySyncerService.ts, config/binaries.ts
> 构建为 js 后会提示路径不存在
* 统一替换为相对路径
=> fix: import path

app/common/adapter/binary/ElectronBinary.ts, app/common/adapter/binary/GithubBinary.ts, app/common/adapter/binary/ImageminBinary.ts, app/common/adapter/binary/NodeBinary.ts, app/common/adapter/binary/NodePreGypBinary.ts, app/common/adapter/binary/NwjsBinary.ts
Fix partial `config/binaries` file path in binary.
Prevent js parsing issues when cnpmcore is required as an npm module.
This is the part that was missed in the previous pr . https://github.com/cnpm/cnpmcore/pull/384
=> fix: config path

app/port/controller/package/SavePackageVersionController.ts, config/config.default.ts, test/port/controller/package/SavePackageVersionController.test.ts
closes https://github.com/cnpm/cnpmcore/issues/388
=> fix: allow publish 10mb tarball package by default

app/core/service/PackageSyncerService.ts, test/core/service/PackageSyncerService/executeTask.test.ts, test/fixtures/registry.npmjs.org/resvg-js.json
closes https://github.com/cnpm/cnpmcore/issues/397
=> feat: auto sync package's optionalDependencies

app/common/adapter/NPMRegistry.ts
This reverts commit 282abf692045f4660831ceacf7e1e7851ff58241.
=> Revert "fix: should sync package deps by default (#400)"

app/common/constants.ts, app/core/service/PackageSyncerService.ts, app/infra/NFSClientAdapter.ts, config/config.default.ts, test/common/adapter/binary/ImageminBinary.test.ts, test/core/service/PackageSyncerService/executeTask.test.ts
> 为了避免部分 npm 包误封、误删，导致生产环境影响，新增 syncDeleteMode 配置，允许自定义同步策略
* 新增 `syncDeleteMode` : 'ignore' | 'block' | 'delete'
* delete: 目前默认值，同步删包事件
* ignore: 忽略 upstream 所有删包事件
* block: 不做物理删除，只新增 block 记录，不允许访问，除非管理员手动恢复并更新 `syncPackageBlockList`
* `npm-security-holder` 场景也判断为删包事件
* 更新原有删包流程，统一处理，调整部分日志输出
---------------
> New `syncDeleteMode` to allow custom syncing policy to avoid some npm packages being blocked or deleted by mistake.
* Add `syncDeleteMode` : 'ignore' | 'block' | 'delete'
* delete: by default, sync delete events
* ignore: ignore all upstream delete events
* block: only add block records, cant access unless the administrator manually restores and update `syncPackageBlockList`.
* `npm-security-holder` event is also determined to be a delete event
* Update the original packet …
=> feat: sync delete mode

app/core/service/TaskService.ts, test/core/service/PackageSyncerService/createTask.test.ts
> 相同任务并发执行时，如果上游有 changesStream 事件，可能会导致版本被错误删除。
* 撤销 https://github.com/cnpm/cnpmcore/pull/352 的变更，我们已在 https://github.com/cnpm/cnpmcore/pull/361 中解决了事件实时性问题
------------
> Concurrent execution of the same task with changesStream events may cause versions to be deleted incorrectly.
* revert https://github.com/cnpm/cnpmcore/pull/352, since we have fixed in https://github.com/cnpm/cnpmcore/pull/361
=> fix: distinct processing task

app.ts, app/core/typing.ts
> https://github.com/cnpm/cnpmcore/pull/367 tegg-v3 升级后，service 改为 Singleton，无法通过 ctx 上下文获取
* 修改 app 内 Service 获取方式
* 移除废弃的 typing.ts 声明
------------
> https://github.com/cnpm/cnpmcore/pull/367 Service has been refactored to Singleton in tegg-v3 , which can't be inited with context anymore.
* Update Service init logic in appHook
* Remove the deprecated typing.ts
=> fix: changesStream suspend

app.ts, app/core/service/ChangesStreamService.ts, test/core/service/ChangesStreamService.test.ts
> 当前请求 changesStream 失败时，需等待 15 分钟超时调度。
* 原 suspendTaskWhenExit 重构为 suspendSync ，支持传入 exit 参数，控制是否继续等待
* 请求 changesStream 失败时，主动挂起任务
------
> Wait 15 minutes for timeout scheduling if the current request changesStream fails
* `suspendTaskWhenExit` is refactored to `suspendSync`, add exit parameter to control whether to exiting the queue
* Suspend task when request changesStream fails
=> feat: retry changes task when current work error

package.json
skip snyk download
```
[09:07:45] [4/4] scripts.postinstall npm-cli-login@1.0.0 › snyk@^1.124.1 run "node wrapper_dist/bootstrap.js exec", root: "/root/workspace/npmmirror-registry_main/node_modules/_snyk@1.1117.0@snyk"
[09:07:45] Downloading from 'https://static.snyk.io/cli/v1.1117.0/snyk-linux' to '/root/workspace/npmmirror-registry_main/node_modules/_snyk@1.1117.0@snyk/wrapper_dist/snyk-linux'
```
=> test: use @cnpmjs/npm-cli-login instead of npm-cli-login

app/port/controller/package/ShowPackageController.ts, test/port/controller/package/ShowPackageController.test.ts
> manifest 读取场景弱依赖 redis
* 添加 try-catch 防止 redis 请求失败导致读取失败
* 读取完成后异步设置缓存
----
> Redis dependency from manifest with weak scene dependence:
* Adds try-catch to prevent reading failure from redis interruption.
* Asynchronously sets cache after reading is complete.
=> feat: redis weak

app/port/controller/AbstractController.ts, config/config.default.ts, test/port/controller/package/ShowPackageController.test.ts
> 在禁止自动创建同步任务时也可以关闭 redirectNotFound，实现在私有化部署时用户仅能使用当前仓库内已有的依赖
--------------
> Allow to turn off redirectNotFound when disabling the automatic creation of sync tasks, enabling users to use only existing dependencies in the current repository when deploying privately.
=> feat: redirect not found can be false when syncMode='none'

app/core/service/TaskService.ts, app/repository/util/ModelConvertor.ts, test/schedule/TaskTimeoutHandler.test.ts
> 💥 TaskTimeoutHandler did not have try-catch, the redis lock will cause all queues to fail when a single task update failed.
* 🛡️ Added try-catch statements in TaskTimeoutHandler.
* 🚧 Restricted updates to the primary key when updating the model in ModelConvertor.
---------------
> 💥 TaskTimeoutHandler 未添加 try-catch，且有同步锁，导致单个任务更新异常时，所有队列不生效
* 🛡️ TaskTimeoutHandler 统一添加 try-catch
* 🚧 ModelConvertor 更新模型时，统一限制不允许更新主键
=> fix: timeout handler not work

app/core/service/PackageSyncerService.ts, test/core/service/PackageSyncerService/executeTask.test.ts, test/core/service/PackageSyncerService/getTaskRegistry.test.ts
> Fixed the issue where the registry was not correctly matched when synchronizing scoped packages for the first time
* Add scope params in initSpecRegistry
------------
> 修复初次同步 scope 包，未正确匹配 registry 的问题
* 修改 initSpecRegistry 方法，统一传入 scope 参数
=> fix: init sync spec registry

.github/workflows/chatgpt-cr.yml, .github/workflows/cr.yml, app/port/controller/package/RemovePackageVersionController.ts, test/cli/npm/install.test.ts, test/fixtures/@cnpm/foo-2.0.0/package.json, test/port/controller/package/ShowPackageController.test.ts
closes https://github.com/cnpm/cnpmcore/issues/435
=> fix: allow to remove the package entity

app/common/constants.ts, app/port/controller/AccessController.ts, test/TestUtil.ts, test/cli/npm/access.test.ts, test/cli/npm/install.test.ts, test/port/controller/AccessController/listCollaborators.test.ts, test/port/controller/AccessController/listPackagesByUser.test.ts
> Supports partial npm access query commands. https://github.com/cnpm/cnpmcore/issues/64
* The following commands are supported:
* `npm access list packages [<user>|<scope>|<scope:team> [<package>]`
* `npm access list collaborators [<package> [<user>]]`
* Added `/-/package/:fullname/collaborators` and `/-/org/:username/package` interfaces.
* Error code logic is consistent with the npm registry.
--------------
> 支持部分 npm access 查询命令 https://github.com/cnpm/cnpmcore/issues/64
* 支持如下命令:
* `npm access list packages [<user>|<scope>|<scope:team> [<package>]`
* `npm access list collaborators [<package> [<user>]]`
* 新增 `/-/package/:fullname/collaborators` 及 `/-/org/:username/package`  接口
* 错误码逻辑和 npm registry 保持一致
=> feat: support npm access command

app/infra/AuthAdapter.ts
默认自带的`authUrl` 更新为配置为 `registry` 会更合理，这里更多考虑到私有部署的情况下一般会有多层反向代理，直接使用 `ctx.href` 意义不大
=> fix: update webauth default URL to registry

app/core/service/PackageSyncerService.ts, sql/1.10.0.sql
closes https://github.com/cnpm/cnpmcore/issues/438
=> fix: skip tag name out of utf8mb3

app/common/FileUtil.ts, app/common/adapter/NPMRegistry.ts, app/core/entity/Task.ts, app/core/service/BinarySyncerService.ts, app/core/service/PackageSyncerService.ts, app/port/controller/PackageSyncController.ts, app/port/typebox.ts, test/core/service/PackageSyncerService/executeTask.test.ts
The upstream repository carries authentication header information via task parameters when alwaysAuth is enabled
---
上游仓库开启alwaysAuth时通过任务参数携带认证头信息
=> feat: create sync task with auth header

app/common/FileUtil.ts, app/core/service/PackageVersionFileService.ts, test/common/FileUtil.test.ts, test/port/controller/PackageVersionFileController/raw.test.ts
avoid "zlib: unexpected end of file"
=> fix: download tgz file to local file before untar it

config/config.default.ts, test/port/controller/PackageBlockController/blockPackage.test.ts, test/port/controller/package/ShowPackageController.test.ts, test/port/controller/package/ShowPackageVersionController.test.ts
follow registry.npmjs.org default value
=> fix: set cache-control default value to "public, max-age=300"

app/core/service/PackageManagerService.ts, test/core/service/PackageSyncerService/executeTask.test.ts
> Fixed the idempotent issue during unpublish pkg, which caused repeated triggering of change events and endless sync loops for downstream registries.
* 🐞 Add idempotent check during unpublish; skip when the package has already been unpublished.
-------------
> 修复 unpublish 时未做幂等控制，导致删包时，不断触发 change 事件，下游 registry 不断 sync 导致任务循环
* 🐞 统一在 unpublish 进行幂等判断，如果该包已 unpublish，则跳过
=> fix: unpublish idempotent

INTEGRATE.md, app/common/typing.ts, app/port/config.ts, app/port/controller/HomeController.ts, config/config.default.ts
> Make the method for tegg integration mode to be more user-friendly.
* 🤖 Automatically add config.cnpmcore type hints.
* 🧶 Export the default `cnpmcoreConfig` , which needs to be explicitly declared for app config.
* 📚 Supplement the documentation and field definitions.
------
> 对于 egg 集成模式，提供更加友好的自定义配置方式。
* 🤖 自动添加 config.cnpmcore 类型提示
* 🧶 输出默认的 cnpmcoreConfig 对象，应用集成需显式声明，防止新增配置丢失
* 📚 补充文档及字段定义信息
=> feat: easy config

app/common/constants.ts, app/common/typing.ts, app/core/service/RegistryManagerService.ts, app/port/config.ts, config/config.default.ts
> New CnpmcoreConfig type to handle compatibility issues https://github.com/cnpm/cnpmcore/pull/475
1. 🆕 add a new CnpmcoreConfig in port/config, referenced in config.default.ts
2. 🆕 add `ChangesStreamMode` enums.
-------------
> 新增 CnpmcoreConfig 类型处理兼容问题 https://github.com/cnpm/cnpmcore/pull/475
1. 🆕 新增 CnpmcoreConfig，config.default.ts 中进行引用
2. 🆕 新增 `ChangesStreamMode` 枚举
=> fix: refactor config type

app/port/controller/PackageVersionFileController.ts, test/port/controller/PackageVersionFileController/listFiles.test.ts
> @types packages generally don't configure the main field, will cause infinite loops [exp](https://registry.npmmirror.com/@types/node/20.2.5/files)
1. 🧶 Change the default logic when processing main field
2. 📦 Keep operational logic consistent with unpkg [ref](https://unpkg.com/@types/node@20.2.5/)
--------
> @types 包一般没有配置 main 字段，会导致无限循环 [exp](https://registry.npmmirror.com/@types/node/20.2.5/files)
1. 🧶 修改 main 字段默认逻辑判断口径
2. 📦 操作逻辑和 unpkg 保持一致 [ref](https://unpkg.com/@types/node@20.2.5/)
=> fix: unpkg redirect

app/core/entity/Token.ts, app/core/service/TokenService.ts, app/port/UserRoleManager.ts, app/port/controller/TokenController.ts, app/repository/model/Token.ts, sql/1.16.0.sql, test/port/controller/TokenController/createToken.test.ts
> Add the lastUsedBy field to the Token model
* 🧶 Add `lastUsedBy` field to the token, for platform display.
* 🐞 Fix the issue where the graunlarToken is not expired in read-only scenarios.
------
> 为 Token 模型添加 lastUsedBy 字段
* 🧶 新增 lastUsedBy 字段，记录 token 最近使用时间，用于平台展示
* 🐞 修复 graunlarToken 过期时，只读场景没有禁用的问题
=> feat: token last used at

app/core/service/PackageManagerService.ts, test/port/controller/package/SavePackageVersionController.test.ts
> For private packages published in the current registry, add the "_npmUser" field to align with the npm registry.
* 🧶 Add the "_npmUser" field for new scenarios, without modifying the abbreviated data. Use the following command: curl -H 'Accept: application/vnd.npm.install-v1+json' 'https://registry.npmjs.org/cnpmcore'
* ♻️ Existing data cannot be traced and will not be compensated.
-----
> 对于在当前 registry 发布的私有包，添加 _npmUser 字段，和公网 registry 保持一致
* 🧶 新增 _npmUser 字段，abbreviated 场景不做修改, (via `curl  -H 'Accept: application/vnd.npm.install-v1+json' 'https://registry.npmjs.org/cnpmcore'`)
* ♻️ 存量数据无法回溯，不做补偿
=> feat: add _npmUser

app/core/entity/Token.ts, app/port/controller/TokenController.ts, app/port/controller/UserController.ts, app/repository/UserRepository.ts, test/port/controller/UserController/whoami.test.ts
> add token info when invoke `whoami` to notify the caller about the token's current status.
* 🧶 Add token information to the "whoami" interface.
* 🔨 Modify the query logic for allowedPackages uniformly within the repository.
-----------
> 当使用 granularToken 调用 whoami 信息时，返回当前 token 信息，告知调用方当前 token 状态
* 🧶 在whoami 接口中添加 token 信息
* 🔨 修改 allowedPackages 查询逻辑，统一在 repository 中集成
=> feat: whoami granular

app/core/service/PackageManagerService.ts, test/port/controller/package/ShowPackageController.test.ts
> Add the `_source_registry_manifest` in pkgFullManifest.
* 🧶 Set registryInfo during reading because of the excessive existing data.
* ♻️ The change takes effect when redis cache expired.
----------
> 在 pkgFullManifest 中添加 _source_registry_manifest 相关字段
1. 🧶 存量数据过多，在读取时统一设置，展示当前对应 registryId
2. ♻️ 在读取 db 时生效，需要等缓存过期
=> feat: source registry manifest

app/port/controller/package/UpdatePackageController.ts, test/TestUtil.ts, test/port/controller/package/UpdatePackageController.test.ts
> When update members , infer the userPrefix by default to be compatible with the default npm cli.
* 🧶 When adding a member, query the userPrefix corresponding to the registry.
```
✅ $ npm owner add elrrrrrrr @cnpm/example --registry=http://127.0.0.1:7001
✅ $ npm owner add cnpm:elrrrrrrr @cnpm/example --registry=http://127.0.0.1:7001
```
-------
> 使用 cli 更新成员时，默认推导 userPrefix 信息，兼容 npm 客户端默认流程
* 🧶 添加成员时，查询 registry 对应的 userPrefix
```
✅ $ npm owner add elrrrrrrr @cnpm/example --registry=http://127.0.0.1:7001               
✅ $ npm owner add cnpm:elrrrrrrr @cnpm/example --registry=http://127.0.0.1:7001
```
=> feat: infer userPrefix when update maintainers 

app/port/controller/PackageVersionFileController.ts, app/port/controller/package/ShowPackageVersionController.ts, app/port/typebox.ts, test/port/controller/PackageVersionFileController/listFiles.test.ts, test/port/controller/PackageVersionFileController/raw.test.ts, test/port/controller/PackageVersionFileController/sync.test.ts, test/port/controller/package/ShowPackageVersionController.test.ts
> follow https://github.com/cnpm/cnpmcore/pull/495 after supporting spec, adjust the parameter validation rules
1. 🆕 Add `Spec` validation rule, validating the spec by npa
2. 🛠️ Upgrade versionOrTag to versionSpec to support semver expressions, such as `^2.x || > 3.x`
---------
> follow https://github.com/cnpm/cnpmcore/pull/495 支持 spec 后，调整参数校验规则
1. 🆕 新增 `Sepc` 校验规则，使用 npa 拼接包名进行验证
2. 🛠️ versionOrTag 升级为 versionSpec 支持 semver 表达式，例如 `^2.x || > 3.x`
=> refactor: validate spec

app/core/service/PackageManagerService.ts, app/core/service/PackageSyncerService.ts, app/port/controller/package/UpdatePackageController.ts, test/core/service/PackageSyncerService/executeTask.test.ts
> Some dirty data of userPrefix in the maintainers cannot be cleared during synchronization. Adjust the synchronization logic for maintainers.
1. 🧶 When synchronizing packages, uniformly update the manifest dist.
2. 🛠️ `replacereplacePackageMaintainers` => `replacePackageMaintainersAndDist`
-----
> 部分旧包 maintainer 中的 userPrefix 脏数据同步时由于没有成员变更，无法清除，调整 maintainer 同步逻辑
1. 🧶 包同步时，统一更新 maintainer 对应的 manifest dist
2. 🛠️ `replacereplacePackageMaintainers` => `replacePackageMaintainersAndDist`
=> feat: bulk update maintainers

config/config.default.ts
作为 #465 的实现
1. 将一些常见配置抽出来支持环境变量
2. 将 MYSQL 之类的已有的环境变量统一前缀为 `CNPMCORE`
=> feat: Support environment variable for config :rocket: 

app/port/controller/AbstractController.ts, app/port/controller/package/DownloadPackageVersionTar.ts, test/port/controller/package/DownloadPackageVersionTarController.test.ts
will check package version on database before redirect to nfs store url
closes https://github.com/cnpm/cnpmcore/issues/521
=> fix: should redirect when nfs adapter support url

app/port/controller/package/DownloadPackageVersionTar.ts
https://github.com/cnpm/cnpmcore/pull/522/files#r1234655574
=> fix: avoid db query on sync mode all

package.json
closes https://github.com/cnpm/cnpmcore/issues/530
=> fix: only auto install s3-cnpmcore on Node.js 18+

app/core/service/PackageSyncerService.ts, test/core/service/PackageSyncerService/executeTask.test.ts
> During the syncUpstream process, it will attempt to create sync repeatedly until it times out, when the pkg has been published in the self registry.
1. 🐞 When executing the syncTask, filter out scenarios where the target registry is the self registry.
-------
> 包迁移至当前 registry 时，收到同步请求会产生无效的同步任务，当 `syncUpstream` 时，会尝试重复创建 sync 直到超时。
1. 🐞 syncTask 执行时，先过滤目标 registry 是当前 registry 的场景。
=> fix: sync self pkg

app/port/controller/package/SavePackageVersionController.ts, test/port/controller/package/SavePackageVersionController.test.ts
> pkgs sync from cnpmjs.org may contain uppercase characters.
1. 🧶 Update the validation rules, allow to publish existing packages.
---------
> 部分包从 cnpmjs.org 进行同步，可能含有大写字符
1. 🧶 更新校验规则，允许存量包修改
=> fix: legacy pkg publish

app/port/controller/package/SavePackageVersionController.ts
> remove console.log
----
去除 console.log
=> fix: console

app/core/service/PackageSyncerService.ts, test/core/service/PackageSyncerService/executeTask.test.ts
> Only syncUpstream for default registry,  to optimize the synchronization speed.
* 🧶 Adjust the syncUpstream judgment process.
----
> 仅对公网包进行 syncUpstream 流程处理，内网包没有多级代理流程，优化同步速度。
* 🧶 调整 syncUpstream 判断流程
=> fix: only syncUpstream in default registry

app/core/service/PackageManagerService.ts, test/port/controller/package/SavePackageVersionController.test.ts
> the registryInfo in pkg fullManifest should be updated when the package is migrated to another registry.
1. 🐞 when query from DB, dynamically add registry information.
2. ♻️ when hit cache, updating metadata should already trigger cache modifications.
--------
> 当包从属 registryId 发生变化时，包 manifest 内的信息也需要同步更新
1. 🐞 从 db 读取元信息时，实时添加 registry 信息
2. ♻️ 从缓存读取元信息时，发布或修改元信息时已触发缓存修改
=> fix: update source registry

app/common/PackageUtil.ts, app/port/config.ts, app/port/controller/package/SavePackageVersionController.ts, config/config.default.ts, test/port/controller/package/SavePackageVersionController.test.ts
> Validate the manifest and tarball info to prevent contamination during consumption, closes #542.
1. 🔨 Added the "strictValidateTarballPkg" mode to enable validation, only applicable to the slef registry scenario.
2. 🧶 When the configuration is enabled, validate the relevant fields during publishing, currently only validating the fields affecting consumption.
3. ♻️ No corrective actions will be taken for existing scenario data.
-----
> 发布时校验 manifest 和 tarball 字段是否陪陪，防止消费时被污染 closes #542
1. 🔨 新增 strictValidateTarballPkg 配置，仅对在发布当前 registry 场景下生效
2. 🧶 配置开启时，发布时校验相关字段，目前仅校验影响消费相关字段
3. ♻️ 存量场景数据不做订正处理
=> feat: support strictValidateTarballPkg

app/core/service/TokenService.ts, app/port/UserRoleManager.ts, test/port/controller/TokenController/listTokens.test.ts
> Follow https://github.com/cnpm/cnpmcore/pull/488 , add lastUsedAt for classic tokens.
1. 🧶 Modify the `checkTokenExpired` method to `checkTokenStatus` which update the token field internally.
2. ♻️ No compensation will be made for existing data, and it should be updated by the consuming end.
---------
> Follow https://github.com/cnpm/cnpmcore/pull/488, 为 classic token 也添加 lastUsedAt 信息
1. 🧶 修改 `checkTokenExpired` 方法为 `checkTokenStatus`，内部进行 token 字段更新
2. ♻️ 存量数据不做补偿，由消费端控制
=> feat: add lastUsedAt for classic token

app/port/controller/HomeController.ts, test/port/controller/HomeController/misc.test.ts
> close #551 , 针对未实现的 post 请求添加错误码
1. 🧶 拦截 audit 相关接口 [ref](https://docs.npmjs.com/cli/v9/commands/npm-audit)
2. ♻️ 默认 404 GET 接口不做额外处理
-----
> close #551, add error code for unimplemented post requests
1. 🧶 Intercept audit-related interfaces [ref](https://docs.npmjs.com/cli/v9/commands/npm-audit)
2. ♻️ No additional processing for default 404 GET interfaces.
=> feat: misc router

app/core/service/PackageSyncerService.ts, test/core/service/PackageSyncerService/executeTask.test.ts
> closes #553, fixing the issue introduced by https://github.com/cnpm/cnpmcore/pull/491, which caused an abnormality in the _npmUser field in fullManifest.
1. 🧶 Update the `publish` method to pass in the actual operating publisher information.
2. 🧶 Update the diffMeta function to compare the _npmUser as well.
3. ♻️ Existing data needs to be resynchronized, from 6.2 to 7.20.
-----
> closes #553 , 修复由 https://github.com/cnpm/cnpmcore/pull/491 引入问题，导致 fullManifest 中  _npmUser 字段异常
1. 🧶 更新 .publish 方法，传入实际操作的 publisher 信息
2. 🧶 更新 diffMeta 算法，将 _npmUser 也进行比对
3. ♻️ 存量数据需要重新进行同步，6.2 -> 7.20
=> fix: _npmUser info in fullManifest

app/port/middleware/ErrorHandler.ts
=> fix: don't log NotImplementedError to error log

app/core/service/PackageManagerService.ts, app/core/service/PackageSyncerService.ts, app/repository/PackageRepository.ts, test/core/service/PackageSyncerService/executeTask.test.ts
> Fixed an issue with the `_npmUser` field setting during the initial sync.
1. 🧶 Fixed _npmUser field setting issue during initial sync, should use displayName.
2. 🧶 skip diff abbreviated meta for _npmUser
3. 🤖 Refined some TypeScript definitions, use isEqual to diff metas
-------
> 修复首次同步时，`_npmUser` 字段设置异常
1. 🧶 修复 publisher 匹配，获取逻辑，应当用 displayName 进行匹配
2. 🧶 精简 meta 信息，跳过比较不存在的 _npmUser 字段
2. 🤖 调整部分 ts 定义，使用 isEqual 来进行 diff 比较
=> fix: publisher info

app/core/service/UserService.ts, app/port/controller/TokenController.ts, test/port/controller/TokenController/createToken.test.ts
> Auto init the account when auth
* 🧶 Added `findOrCreateUser` method. Initialize account on both login and authorization, as per the submitted GitHub."
------
> 授权时，默认进行账户初始化
* 🧶 新增 `findOrCreateUser` 方法，登录和授权时均初始化账户
=> feat: signup on auth

app/core/service/BinarySyncerService.ts, test/core/service/BinarySyncerService/executeTask.test.ts
> closes #376: fix issue with incomplete binary file after upstream release or sync failure
* 🧶 Modify the binary `diff` method, adding latest version check method.
* ♻️ Perform additional comparison on the latest version, without modifying existing data.
---------
> 修复 #376 ，兼容上游发布或同步失败后，产物同步不全的问题
* 🧶 调整 binary `diff` 方法，添加最新版本校验逻辑
* ♻️ 对最新版本的子目录进行额外比对，存量数据不做修改
=> feat: revalidate latest version

app/core/service/PackageManagerService.ts, app/port/controller/package/SavePackageVersionController.ts, test/core/service/PackageManagerService/publish.test.ts, test/port/controller/package/SavePackageVersionController.test.ts, test/repository/PackageRepository.test.ts
> closes #574 Fixed the issue where custom tags in publishConfig prevented the default latest tag.
* 🧶 Modified the `savePackageVersion` API, automatically add latest tag if no latest tag.
* 🧶 The publish tag parameter has been changed to tags, triggering corresponding events in batches.
* ♻️ No changes to the package synchronization process.
------
> closes #574 修复 publishConfig 中自定义 tag，导致 latest tag 未设置的问题
* 🧶 修改 savePackageVersion 接口，如果当前包未配置 latest tag，则自动补全
* 🧶 publish tag 参数改为 tags，对应事件分批触发
* ♻️ 包同步流程不做修改
cc  @shinima @peachscript
=> fix: default latest tag

tsconfig.json
https://devblogs.microsoft.com/typescript/announcing-typescript-5-2/#module-and-moduleresolution-must-match-under-recent-node-js-settings
> Option 'moduleResolution' must be set to 'NodeNext' (or left unspecified) when option 'module' is set to 'NodeNext'.
=> fix: should use NodeNext on module and moduleResolution tsconfig

app/core/service/PackageSearchService.ts, app/repository/SearchRepository.ts, docs/elasticsearch-setup.md
> in npm@8 cli, empty author information after executing npm search
* 🐞 Fix: npm-cli author field is empty, need to add publisher-related fields
* 📚 Update API documentation
-----
> npm@8 命令行，执行 npm search 后，author 信息为空
* 🐞 修复 npm-cli author 字段为空，需添加 publisher 相关字段
* 📚 更新文档接口信息
=> fix: author info

app/core/service/PackageSearchService.ts, app/repository/PackageRepository.ts
有些 package 的 license 是个对象，会导致 es 写入失败 https://github.com/cnpm/cnpmcore/issues/585#issuecomment-1706009496
=> fix: fix the issue where the license may be an object

package.json
https://github.com/cnpm/oss-cnpm/pull/29
https://github.com/node-modules/oss-client/pull/12
=> feat: use oss-client v2

app/port/controller/package/DownloadPackageVersionTar.ts, package.json, test/port/controller/package/DownloadPackageVersionTarController.test.ts
make webcontainer can run npm install on cnpmcore registry
=> feat: allow OPTIONS request on tgz downlaod url

config/config.default.ts, test/port/controller/HomeController/cors.test.ts
Access to fetch at 'https://registry.npmmirror.com/isstream/-/isstream-0.1.0.tgz' from origin 'https://foo.com' has been blocked by CORS policy: Method OPTIONS is not allowed by Access-Control-Allow-Methods in preflight response.
=> fix: should set OPTIONS on access-control-allow-methods

app/core/service/PackageSearchService.ts, test/port/controller/package/SearchPackageController.test.ts
=> fix: es query script score syntax fix and add error handler for 404 error

app/core/service/PackageSyncerService.ts, app/port/typebox.ts, app/repository/TaskRepository.ts, test/core/service/PackageSyncerService/executeTask.test.ts, test/port/controller/PackageSyncController/createSyncTask.test.ts
1. 添加新建任务时的重复版本校验，去除执行任务时的版本去重
2. 在strictSyncSpecificVersion开启时，修改为从可用版本中选择latestTag。之前从任务的指定版本中生成latestTag逻辑不正确
=> fix: incorrect latest tag in strict specific version

app/common/PackageUtil.ts, app/core/service/PackageVersionFileService.ts, package.json
closes https://github.com/cnpm/cnpmcore/issues/624
=> fix: use tar fork version to fix memory leak

app/core/service/PackageSearchService.ts, test/port/controller/package/SearchPackageController.test.ts
当搜索关键词为空时，不进行 ES 关键词搜索拼接，返回一个默认的全量数据排名。 close #622
=> fix: should search default packages when text is empty

app/core/service/PackageVersionFileService.ts, test/port/controller/PackageVersionFileController/listFiles.test.ts
> When accessing the unpkg service, when the packages have not yet been synchronized, will lead to multiple synchronization attempts concurrently causing db insert errors.
* 🔒 Added a Redis lock for the `ensurePackageVersionFilesSync` function, with a default timeout of 60 seconds.
* 🥸 Admin PUT requests and the package version auto sync process are not restricted by this.
> 当访问 unpkg 服务时，如果访问存量未同步的包，可能导致多次同步并发报错
* 🔒 为 ensurePackageVersionFilesSync 添加 redis 锁，默认超时 60s
* 🥸 管理员手动 PUT 请求和包同步流程不受限制
=> fix: unpkg lock

app/core/entity/Task.ts, app/core/service/BinarySyncerService.ts, app/core/service/TaskService.ts, test/core/service/HookTriggerService.test.ts
> Since the eventBus#cork , version & tag events are triggered at same time, cause the abnormal triggers of different types of hooks.
* ~~🐞 Fix triggerHook type targetName to be `tagetName:changeId`~~
* 🤖 Only merge sync tasks (binary, package) which in waiting states
--------
> 由于 `eventBus#cork` 机制，版本事件同时触发，导致不同类型 hook 触发异常
* ~~🐞 修改 triggerHook 类型 targetName 为 `包名:changeId`~~
* 🤖 仅合并 waiting 状态下包同步任务
=> fix: hooks triggers

config/binaries.ts
**what:** pkg-fetch provides prebuilt node binaries used by pkg.
**why from yao-pkg:** [vercel/pkg-fetch](https://github.com/vercel/pkg-fetch) was archived, [yao-pkg/pkg-fetch](https://github.com/yao-pkg/pkg-fetch) is currently the most actively maintained fork.
close: #543
=> feat: mirror pkg-fetch from yao-pkg/pkg-fetch

package.json
**问题：**
Node.JS安全性修复导致RSA_PKCS1_PADDING不可用，会报出以下错误：
> RSA_PKCS1_PADDING is no longer supported for private decryption, this can be reverted with --security-revert=CVE-2023-46809。
该PR用于修复以上问题。
参考链接：[https://www.eggjs.org/zh-CN/core/security#revert-cve](https://www.eggjs.org/zh-CN/core/security#revert-cve)
=> fix: fix breaking change about RSA_PKCS1_PADDING.

app/common/adapter/binary/AbstractBinary.ts, app/common/adapter/binary/ChromeForTestingBinary.ts, app/core/service/BinarySyncerService.ts, test/common/adapter/binary/ChromeForTestingBinary.test.ts
closes https://github.com/cnpm/cnpmcore/issues/652
=> fix: only set chrome-for-testing data timestamp after sync task finish

app/core/service/PackageSearchService.ts, app/repository/SearchRepository.ts
在今年 4 月份，npm cli 对 search 做了[一些改动]，在 4 月份以前(npm cli < `v10.6.0`)，采用的是 `maintainers` 字段，而在 https://github.com/npm/cli/pull/7407 后，改为使用: `publisher` 字段。
导致当 npm 版本大于等于 `v10.6.0` 后，search 结果中的 `author` 将变成 `???`，如图：
预期的结果应该为:
当前改动没有为 `es` 增加新的索引，原因是处于以下考虑:
1. es 的 `mapping` 一旦创建，就无法修改（虽然使用了 `dynamic: true` 但无法细粒度的进行控制）
2. 源数据中的 `_npmUser` 已经有相关信息了，没有必要为此浪费额外的磁盘空间
3. 如果想对以前的数据进行更新会比较麻烦，性价比较低
npm cli 老版本: https://github.com/npm/cli/pull/7407/files#diff-4bc15933c685fc9a9ce8be0c13a2f067f5e2b3334bacd6664bdfa7ddc46aedb6L58
npm cli 新版本: https://github.com/npm/cli/pull/7407/files#diff-4bc15933c685fc9a9ce8be0c13a2f067f5e2b3334bacd6664bdfa7ddc46aedb6R162
相关 PR: https://github.com/cnpm/cnpmcore/pull/513
PTAL @Beace @fengmk2 @elrrrrrrr
[一些改动]: https://github.com/npm/cli/pull/7407
=> fix(search): author is `???` in result
