app/core/event/index.ts
app/core/service/PackageManagerService.ts
app/core/service/PackageSyncerService.ts
app/core/service/UserService.ts
app/repository/PackageRepository.ts
test/core/service/PackageSyncerService/executeTask.test.ts
test/port/controller/PackageTagController/removeTag.test.ts

closes https://github.com/cnpm/cnpmcore/issues/28 again

🐛 FIX: Support super big dist-tags sync speeds

---

app/core/entity/Task.ts
app/core/service/PackageSyncerService.ts
app/repository/TaskRepository.ts
test/core/service/PackageSyncerService/executeTask.test.ts
test/core/service/PackageSyncerService/findExecuteTask.test.ts
test/port/controller/PackageSyncController/createSyncTask.test.ts

closes https://github.com/cnpm/cnpmcore/issues/39

🐛 FIX: Dont sync exists waiting task

---

app/common/adapter/NPMRegistry.ts
app/core/service/PackageManagerService.ts
app/core/service/PackageSyncerService.ts
app/schedule/CleanTempDir.ts
app/schedule/SyncPackageWorker.ts
test/core/service/PackageSyncerService/executeTask.test.ts
test/port/controller/PackageController/saveVersion.test.ts
test/schedule/CleanTempDir.test.ts
test/schedule/SyncPackageWorker.test.ts

closes https://github.com/cnpm/cnpmcore/issues/42

🐛 FIX: Handle sync worker error and increae download time

---

app/core/service/PackageSyncerService.ts
app/repository/TaskRepository.ts
test/core/service/PackageSyncerService/executeTask.test.ts
test/port/controller/PackageSyncController/createSyncTask.test.ts

closes https://github.com/cnpm/cnpmcore/issues/48

🐛 FIX: Avoid concurrent sync taks

---

.gitignore
app/port/controller/AbstractController.ts
app/port/controller/PackageSyncController.ts
app/port/controller/package/DownloadPackageVersionTar.ts
app/port/controller/package/RemovePackageVersionController.ts
app/port/controller/package/SavePackageVersionController.ts
app/port/controller/package/ShowPackageController.ts
app/port/controller/package/ShowPackageVersionController.ts
app/port/controller/package/UpdatePackageController.ts
app/port/middleware/ErrorHandler.ts
app/schedule/SyncPackageWorker.ts
config/config.default.ts
config/config.unittest.ts
test/port/controller/PackageSyncController/createSyncTask.test.ts
test/port/controller/PackageSyncController/showSyncTask.test.ts
test/port/controller/PackageSyncController/showSyncTaskLog.test.ts
test/port/controller/package/DownloadPackageVersionTarController.test.ts
test/port/controller/package/RemovePackageVersionController.test.ts
test/port/controller/package/SavePackageVersionController.test.ts
test/port/controller/package/ShowPackageController.test.ts
test/port/controller/package/ShowPackageVersionController.test.ts
test/port/controller/package/UpdatePackageController.test.ts
test/schedule/SyncPackageWorker.test.ts

closes https://github.com/cnpm/cnpmcore/issues/31

📦 NEW: Support sync all and none mode

---

app/port/middleware/Tracing.ts
app/schedule/CheckRecentlyUpdatedPackages.ts
package.json
test/.setup.ts
test/port/controller/package/DownloadPackageVersionTarController.test.ts
test/port/middleware/AlwaysAuth.test.ts
test/port/middleware/Tracing.test.ts
test/schedule/CheckRecentlyUpdatedPackages.test.ts
test/schedule/CleanTempDir.test.ts
test/schedule/SyncPackageWorker.test.ts

closes https://github.com/cnpm/cnpmcore/issues/9

📦 NEW: Sync recently updated packages from npm

---

app/common/enum/Task.ts
app/core/entity/Task.ts
app/core/service/ChangesStreamService.ts
app/core/service/PackageSyncerService.ts
app/port/controller/PackageSyncController.ts
app/repository/TaskRepository.ts
app/repository/model/Task.ts
app/schedule/ChangesStreamWorker.ts
config/config.default.ts
config/config.unittest.ts
test/port/controller/PackageSyncController/createSyncTask.test.ts
test/schedule/ChangesStreamWorker.test.ts

- https://github.com/npm/registry-follower-tutorial
- https://github.com/cnpm/cnpmjs.org/blob/master/sync/changes_stream_syncer.js

📦 NEW: subscribe changes from changes_stream

---

app/port/controller/UserController.ts
test/port/controller/UserController/showUser.test.ts

closes https://github.com/cnpm/cnpmcore/issues/56

👌 IMPROVE: Show user name when user exists

---

app.ts
app/port/controller/HomeController.ts
app/repository/PackageRepository.ts
app/repository/PackageVersionDownloadRepository.ts
app/schedule/UpdateTotalData.ts
test/port/controller/HomeController/showTotal.test.ts
test/schedule/CleanTempDir.test.ts

```js
{
last_pacakge: '@cnpm/home2',
last_pacakge_version: '@cnpm/home1@1.0.1',
doc_count: 2,
doc_version_count: 3,
download: {
today: 3,
yesterday: 1,
thisweek: 4,
thismonth: 5,
thisyear: 6,
lastweek: 1,
lastmonth: 1,
lastyear: 1
},
update_seq: 0,
sync_model: 'none',
sync_changes_steam: {},
instance_start_time: '2021-12-25T03:33:40.845Z',
node_version: 'v16.13.1',
app_version: '0.0.2',
engine: 'mysql'
}
```

📦 NEW: Show total data on home page request

---

README.md
app.ts
app/core/entity/Change.ts
app/core/event/ChangesStream.ts
app/core/event/index.ts
app/core/service/ChangesStreamService.ts
app/core/service/PackageManagerService.ts
app/port/controller/ChangesStreamController.ts
app/repository/ChangeRepository.ts
app/repository/model/Change.ts
config/config.default.ts
package.json
sql/init.sql
test/port/controller/ChangesStreamController/listChanges.test.ts

closes https://github.com/cnpm/cnpmcore/issues/70

📦 NEW: Support changes stream

---

app/core/entity/Task.ts
app/core/service/TaskService.ts
test/core/service/PackageSyncerService/findExecuteTask.test.ts

```
[PositionNotEqualToLengthError]: Position is not equal to file length
```

🐛 FIX: Reset log path before execute task again

---

app/common/adapter/binary/SqlcipherBinary.ts
app/core/service/BinarySyncerService.ts
config/binaries.ts
test/common/adapter/binary/SqlcipherBinary.test.ts

https://github.com/journeyapps/node-sqlcipher

📦 NEW: Sync sqlcipher binary

---

app/common/adapter/binary/ImageminBinary.ts
app/core/service/BinarySyncerService.ts
config/binaries.ts
test/common/adapter/binary/ImageminBinary.test.ts

📦 NEW: Sync imagemin binary

---

config/config.default.ts
config/plugin.ts
package.json
test/port/controller/HomeController/cors.test.ts
test/port/controller/HomeController/ping.test.ts

https://github.com/cnpm/cnpmcore/issues/33

📦 NEW: Allow CORS

---

app.ts
app/port/binary.html
app/port/controller/BinarySyncController.ts
test/port/controller/BinarySyncController/showBinary.test.ts

closes https://github.com/cnpm/cnpmcore/issues/84

📦 NEW: Add binary index html

---

app/core/service/PackageSyncerService.ts
test/core/service/PackageSyncerService/executeTask.test.ts

closes https://github.com/cnpm/cnpmcore/issues/97

🐛 FIX: Make sure dist-tags sync between remote and local

---

DEVELOPER.md

https://github.com/cnpm/cnpmcore/issues/111

docs📝:  Update DEVELOPER.md

---

app/common/adapter/NPMRegistry.ts
app/core/entity/Task.ts
app/core/service/PackageSyncerService.ts
app/port/controller/DownloadController.ts
app/port/controller/PackageSyncController.ts
app/port/typebox.ts
app/repository/PackageVersionDownloadRepository.ts
config/config.default.ts
test/common/adapter/binary/PuppeteerBinary.test.ts
test/core/service/PackageSyncerService/executeTask.test.ts
test/port/controller/PackageSyncController/createSyncTask.test.ts

closes https://github.com/cnpm/cnpmcore/issues/108

📦 NEW: Sync download data from old registry

---

app/core/service/PackageSyncerService.ts

closes https://github.com/cnpm/cnpmcore/issues/115:

🐛 FIX: Refresh manifests when remote version not exists

---

app/common/FileUtil.ts
app/core/service/PackageSyncerService.ts
app/core/service/TaskService.ts
test/core/service/PackageSyncerService/executeTask.test.ts

https://registry.nlark.com/-/package/geckodriver/syncs/61f395ce6f424983df998c74/log

👌 IMPROVE: Auto retry if network request error

---

app/common/adapter/NPMRegistry.ts

e.g.: ECONNREFUSED
request manifests error: RequestError: connect ECONNREFUSED 116.0.89.227:443

👌 IMPROVE: retry on http request error

---

app/core/service/PackageSyncerService.ts
test/core/service/PackageSyncerService/executeTask.test.ts

closes https://github.com/cnpm/cnpmcore/issues/126

🐛 FIX: Auto fix maintainers

---

sql/init.sql

https://github.com/cnpm/cnpmcore/issues/132#issuecomment-1025058266

👌 IMPROVE: Add index on package_version_downloads

---

app/core/service/PackageSyncerService.ts
test/core/service/PackageSyncerService/executeTask.test.ts

closes https://github.com/cnpm/cnpmcore/issues/131

👌 IMPROVE: Should unpublish package on 404

---

app/core/service/BinarySyncerService.ts

https://r.cnpmjs.org/-/binary/node/syncs/61fcda3b61ee1f36009ddd8c/log

🐛 FIX: Save changed date on exists binary item

---

app/common/adapter/binary/NodeBinary.ts
test/common/adapter/binary/NodeBinary.test.ts

GET https://r.cnpmjs.org/-/package/@cabindao/nft-passport-contracts/syncs/61fd665f667326a3a5f7e384/log
```
[/v14.0.0-nightly20200204ee9e689df2/] ❌ [0.0] Download https://nodejs.org/download/nightly/v14.0.0-nightly20200204ee9e689df2/node-v14.0.0-nightly20200204ee9e689df2-win-x86.7z 
error: DownloadStatusInvalidError: Download https://nodejs.org/download/nightly/v14.0.0-nightly20200204ee9e689df2/node-v14.0.0-nightly20200204ee9e689df2-win-x86.7z 
status(403) invalid
```

🐛 FIX: Skip zero size file

---

app/core/service/PackageSyncerService.ts
test/core/service/PackageSyncerService/executeTask.test.ts

closes https://github.com/cnpm/cnpmcore/issues/144

🐛 FIX: Should auto sync removed versions

---

config/binaries.ts

github: https://github.com/eugeneware/ffmpeg-static

NEW: Sync ffmpeg-static binary

---

app/core/service/PackageSyncerService.ts
test/core/service/PackageSyncerService/executeTask.test.ts

closes https://github.com/cnpm/cnpm/issues/362

🐛 FIX: Recheck version data in database

---

app/port/controller/UserController.ts

修改为：https://github.com/npm/npm-profile/blob/main/lib/index.js#L127

📖 DOC:  Modify link“ https://github.com/npm/npm-profile/blob/main/index.js#L126” 404 question

---

app/port/controller/TokenController.ts

📖 DOC: fix not exists links

---

app/common/adapter/binary/ElectronBinary.ts
app/common/adapter/binary/GithubBinary.ts
app/core/service/BinarySyncerService.ts
config/binaries.ts
test/common/adapter/binary/ElectronBinary.test.ts

support both `/vX.Y.Z/` and `/X.Y.Z/` dir prefix
- closes https://github.com/cnpm/cnpmjs.org/issues/1712
- closes https://github.com/cnpm/cnpmjs.org/issues/1588

👌 IMPROVE: Compatible electron binary sync

---

config/binaries.ts

closes https://github.com/cnpm/cnpm/issues/364

📦 NEW: Sync npm binary from github

---

config/binaries.ts

For a description see: https://github.com/cnpm/mirrors/pull/285
cc: @fengmk2

feat: add electron nightly version support

---

app/core/service/PackageManagerService.ts
app/core/service/PackageSyncerService.ts
test/TestUtil.ts
test/port/controller/package/SavePackageVersionController.test.ts

closes https://github.com/cnpm/cnpmcore/issues/187

📦 NEW: Return libc field on abbreviated manifests

---

app/core/entity/PackageVersionManifest.ts
app/core/event/StoreManifest.ts
app/repository/PackageRepository.ts
app/repository/model/PackageVersionManifest.ts
config/config.default.ts
sql/init.sql
test/TestUtil.ts
test/core/event/StoreManifest.test.ts

📦 NEW: Store package version manifest to database

---

app/core/service/PackageSyncerService.ts
config/config.default.ts
test/core/service/PackageSyncerService/executeTask.test.ts

📦 NEW: Add force upper case list

---

app/common/adapter/CacheAdapter.ts
app/common/adapter/QueueAdapter.ts
app/core/entity/Task.ts
app/core/service/BinarySyncerService.ts
app/core/service/ChangesStreamService.ts
app/core/service/PackageSyncerService.ts
app/core/service/TaskService.ts
app/repository/TaskRepository.ts
app/schedule/TaskTimeoutHandler.ts
test/.setup.ts
test/common/adapter/BugVersionStore.test.ts
test/common/adapter/CacheAdapter.test.ts
test/core/service/PackageSyncerService/findExecuteTask.test.ts
test/core/service/TaskService/findExecuteTask.test.ts
test/port/controller/PackageSyncController/createSyncTask.test.ts
test/port/controller/PackageSyncController/showSyncTask.test.ts
test/port/controller/package/ShowPackageController.test.ts
test/schedule/ChangesStreamWorker.test.ts
test/schedule/SyncPackageWorker.test.ts
test/schedule/TaskTimeoutHandler.test.ts

closes https://github.com/cnpm/cnpmcore/issues/203

👌 IMPROVE: Use task queue on redis instead of MySQL

---

config/binaries.ts
test/common/adapter/binary/BucketBinary.test.ts

closes https://github.com/cnpm/cnpmcore/issues/209

👌 IMPROVE: Sync prisma all_commits dir

---

app/common/PackageUtil.ts
app/core/service/PackageManagerService.ts
app/core/service/PackageSyncerService.ts
test/core/service/PackageSyncerService/executeTask.test.ts

closes https://github.com/cnpm/cnpm/issues/374

🐛 FIX: Auto resync hasInstallScript property

---

config/binaries.ts

Update binaries.ts add ali-usb_ctl

---

DEVELOPER.md
docker-compose.yml
docs/setup.md
test/prepare.ts

feat: dockerfile

---

app/core/service/PackageManagerService.ts
test/TestUtil.ts
test/core/service/PackageSyncerService/executeTask.test.ts
test/port/controller/package/SavePackageVersionController.test.ts
test/schedule/ChangesStreamWorker.test.ts

closes https://github.com/cnpm/cnpmcore/issues/223

🐛 FIX: Use latest version description and so on

---

app/common/adapter/QueueAdapter.ts
app/core/service/PackageSyncerService.ts
app/core/service/TaskService.ts
config/config.default.ts
test/core/service/PackageSyncerService/executeTask.test.ts

If task queue in high water level, auto limit create task speed

📦 NEW: Auto disable sync upstream and skip dependencies

---

app/common/adapter/binary/PlaywrightBinary.ts
app/core/service/BinarySyncerService.ts
config/binaries.ts
test/common/adapter/binary/PlaywrightBinary.test.ts

Fixes https://github.com/cnpm/cnpm/issues/359
pick from https://github.com/cnpm/cnpmcore/pull/232

📦 NEW: Add playwright binary sync support

---

app/common/FileUtil.ts

fix: filename too long

---

app/port/controller/ChangesStreamController.ts
app/repository/ChangeRepository.ts
test/port/controller/ChangesStreamController/listChanges.test.ts
test/repository/ChangeRepository.test.ts

fix: query changes with order by id asc

---

app/port/UserRoleManager.ts
test/port/controller/package/UpdatePackageController.test.ts

https://github.com/cnpm/cnpmcore/pull/21/files
https://github.com/pnpm/pnpm/blob/12aa1e2e19e5e0b568f1d2d042901401046bded3/packages/config/src/index.ts#L255

fix: valid npm client with correct pattern

---

app/port/UserRoleManager.ts
config/config.default.ts
test/port/controller/package/UpdatePackageController.test.ts

- 修复 admin 不能修改包信息问题 #225 
- 将 npm client&version check 抽离到配置文件中

修复 admin 不能修改包信息问题 & 将 npm client&version check 抽离到配置文件中

---

config/binaries.ts

mirror  for [skia-canvas](https://github.com/samizdatco/skia-canvas/blob/main/package.json#L48)

feat(mirror): add skia-canvas mirror

---

app/common/SyncUtil.ts
test/port/controller/package/ShowPackageController.test.ts

🤖 TEST: show package not use cache if isSync

---

config/binaries.ts

Repo URL: https://github.com/node-webrtc/node-webrtc
Npm URL: https://www.npmjs.com/package/wrtc
Npm config: `wrtc_binary_host_mirror`

feat: add node-webrtc mirror

---

app/common/adapter/binary/NodePreGypBinary.ts
test/common/adapter/binary/NodePreGypBinary.test.ts

close https://github.com/cnpm/cnpmcore/pull/274

🐛 FIX: Handle binary configuration value

---

app/core/entity/Task.ts
app/repository/TaskRepository.ts
app/repository/model/Task.ts
sql/init.sql
test/repository/TaskRepository.test.ts

impl idempotent save for task
Refs:
- https://github.com/cnpm/cnpmcore/issues/282

feat: add bizId for task

---

app/common/enum/Hook.ts
app/core/entity/Hook.ts
app/core/service/HookManageService.ts
app/core/service/TaskService.ts
app/port/UserRoleManager.ts
app/port/controller/HookController.ts
app/port/controller/convertor/HookConvertor.ts
app/port/typebox.ts
app/repository/HookRepository.ts
app/repository/TaskRepository.ts
app/repository/model/Hook.ts
config/config.default.ts
sql/init.sql
test/core/service/HookManageService/createHook.test.ts
test/core/service/HookManageService/deleteHook.test.ts
test/core/service/HookManageService/getHookByOwnerId.test.ts
test/core/service/HookManageService/updateHook.test.ts
test/port/controller/hook/HookController.test.ts

Refs:
- https://github.com/cnpm/cnpmcore/issues/282
- https://github.com/npm/registry/blob/master/docs/hooks/endpoints.md

feat: impl hooks api

---

app/core/service/ChangesStreamService.ts

* 🐞 修复 changesStream 返回空列表，task 状态不更新的问题

fix: changes stream empty

---

app/core/service/TaskService.ts
test/core/service/TaskService/findExecuteTask.test.ts

* 🚗 findExecuteTask 自动获取下一个满足条件的 task

feat: auto get next valid task

---

DEVELOPER.md
config/config.default.ts
docker-compose.yml
package.json

```
2022-09-24 09:06:04,812 INFO 1793 [-/127.0.0.1/10567ea0-3ba5-11ed-a8c6-6f52da8076ba/2.946ms GET /foo] [Tracing] auth: 0, npm-command: -, referer: -, user-agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
[sql-debug] [20.193ms] SELECT * FROM `packages` WHERE `scope` = '' AND `name` = 'foo' LIMIT 1
```

👌 IMPROVE: Enable phpmyadmin and DEBUG_LOCAL_SQL by default

---

config/config.default.ts
package.json

https://github.com/eggjs/egg/issues/4847

👌 IMPROVE: use urllib3 instead

---

app/port/schedule/SyncPackageWorker.ts
config/config.default.ts

https://github.com/cnpm/cnpmcore/blob/0d8a667b3fdc4cef0958353d92f407b766cc6b9f/app/schedule/SyncPackageWorker.ts#L10

🐛 FIX: Should run sync package on all worker

---

app/common/adapter/binary/ApiBinary.ts
test/common/adapter/binary/ApiBinary.test.ts

> API Binary 场景下，解析路径异常
* 更新配置读取路径

fix: api binary host config

---

app/common/adapter/binary/AbstractBinary.ts
app/common/adapter/binary/BucketBinary.ts
app/common/adapter/binary/GithubBinary.ts
app/common/adapter/binary/ImageminBinary.ts
app/common/adapter/binary/NodeBinary.ts
app/common/adapter/binary/NodePreGypBinary.ts
app/core/service/BinarySyncerService.ts
app/port/controller/BinarySyncController.ts
app/port/schedule/CreateSyncBinaryTask.ts
app/port/typebox.ts
config/binaries.ts
test/core/service/BinarySyncerService/createTask.test.ts

> restrict binaryName type , the single source is the `config/binary.js` file.
* export `BinaryName` & `CategoryName` type
* use `BinaryNameRule` typebox validator in controller
* `binaryName: string` => `binaryName: BinaryName`

refactor: Restrict binaryName types

---

package.json
test/common/adapter/binary/ApiBinary.test.ts

https://github.com/eggjs/egg-bin/pull/217

test: use egg-bin v6

---

app/port/controller/BinarySyncController.ts
app/port/typebox.ts
test/port/controller/BinarySyncController/showBinary.test.ts

closes https://github.com/cnpm/cnpmcore/issues/395

fix: forbidden non-ascii binary subpath

---

tsconfig.json

https://typestrong.org/ts-node/docs/swc/

test: use ts-node with swc

---

INTEGRATE.md
README.md

> 新增集成文档，完善 https://github.com/cnpm/cnpmcore/pull/411 SSORequest 文档说明
* 新增 INTEGRATE.md 文档
* README.md 增加对应链接
-----------
> New integration documentation  for https://github.com/cnpm/cnpmcore/pull/411
* Add INTEGRATE.md
* Add link in README.md

feat: add integrate doc

---

DEVELOPER.md
package.json
prepare-database.sh
test/TestUtil.ts
test/prepare.ts
tsconfig.json

> Remove ts-node dependency and do DB initialization via npm scripts hook and bash script.
* Added prepare-database.sh
* Remove swc & ts-node, since swc `useDefineForClassFields` will cause leoric create error [ref](https://github.com/TypeStrong/ts-node/blob/fd438213ad3b3e1bcabea48627255b8be74c1c24/src/transpilers/swc.ts#L229), which can't customize
--------------
> 删除 ts-node 依赖，通过 npm scripts hook 和 bash 来进行 DB 初始化工作
* 新增 prepare-database.sh 处理 db 初始化工作
* 删除 ts-node 及 swc，swc 新版开启 `useDefineForClassFields` 会导致 leoric 创建对象失败，且无法自定义, [ref](https://github.com/TypeStrong/ts-node/blob/fd438213ad3b3e1bcabea48627255b8be74c1c24/src/transpilers/swc.ts#L229)一并去除

chore: remove ts-node

---

app/port/login.html

使用 gw.alipayobjects.com 的CDN源替换 bootcdn
-------------------------------
Update the CDN of JS resource to gw.alipayobjects.com

fix: update login assets cdn url

---

app/common/constants.ts
app/port/controller/AbstractController.ts
app/port/controller/PackageSyncController.ts
app/port/schedule/CheckRecentlyUpdatedPackages.ts
app/port/schedule/SyncPackageWorker.ts
config/config.default.ts
test/port/controller/PackageSyncController/createSyncTask.test.ts

feat: allow admin to sync package only

---

.github/workflows/nodejs.yml
config/plugin.ts
package.json

closes https://github.com/cnpm/cnpmcore/issues/444

feat: add health checker for slb

---

app.ts
app/core/service/PackageSyncerService.ts
config/config.default.ts
package.json

And fix registry error response cause data return null bug

feat: enable sql logger

---

app/core/service/PackageManagerService.ts

> Adjust the logic for unpublishing a package
* 🧶 Determine if a call to unpublish within the removePackageVersion function
* ♻️ Remove`forceRefresh` in unpublishPackage
-------
> 调整 unpublish package 逻辑
* 🧶 removePackageVersion 内判断是否需要调用 unpublish
* ♻️ unpublishPackage 删除 forceRefresh 逻辑

refactor: unpublish logic

---

app/common/adapter/binary/AbstractBinary.ts
app/common/adapter/binary/ApiBinary.ts
app/common/adapter/binary/BucketBinary.ts
app/common/adapter/binary/ChromeForTestingBinary.ts
app/common/adapter/binary/CypressBinary.ts
app/common/adapter/binary/GithubBinary.ts
app/common/adapter/binary/ImageminBinary.ts
app/common/adapter/binary/NodeBinary.ts
app/common/adapter/binary/NodePreGypBinary.ts
app/common/adapter/binary/PlaywrightBinary.ts
app/common/adapter/binary/PrismaBinary.ts
app/common/adapter/binary/PuppeteerBinary.ts
app/common/adapter/binary/SqlcipherBinary.ts
app/common/enum/Binary.ts
app/core/service/BinarySyncerService.ts
config/binaries.ts
test/common/adapter/binary/BucketBinary.test.ts
test/common/adapter/binary/PrismaBinary.test.ts
test/fixtures/list-binaries.prisma-orm.workers.dev/61023c35d2c8762f66f09bc4183d2f630b541d08-darwin-arm64.json
test/fixtures/list-binaries.prisma-orm.workers.dev/61023c35d2c8762f66f09bc4183d2f630b541d08.json

closes https://github.com/cnpm/cnpmcore/issues/473

feat: sync prisma binary from R2

---

app/common/adapter/binary/PrismaBinary.ts
app/core/service/BinarySyncerService.ts
test/common/adapter/binary/PrismaBinary.test.ts

https://github.com/cnpm/cnpmcore/issues/472#issuecomment-1562452369

fix: use S3 url to download file

---

.github/workflows/release.yml
app/core/service/TokenService.ts
app/core/service/UserService.ts
app/port/UserRoleManager.ts

> Export `getUserAndToken` method for authorization parsing in integrate mode.
1. 🧶 TokenService adds getUserAndToken method
----------
> 暴露 `getUserAndToken` 方法进行 authorization 解析，面向集成模式的场景
1. 🧶 TokenService 新增 `getUserAndToken` 方法

feat: export getUserAndToken

---

app/core/service/PackageVersionFileService.ts
app/infra/NFSClientAdapter.ts
test/port/controller/PackageVersionFileController/listFiles.test.ts
test/port/controller/PackageVersionFileController/raw.test.ts
test/port/controller/PackageVersionFileController/sync.test.ts

closes https://github.com/cnpm/cnpmcore/issues/482

fix: use package version publishTime instead of file mtime

---

app/core/event/ChangesStream.ts
test/core/event/ChangesStream.test.ts

> Fix hookEnable config does not take effect
* 🐞 Modify config key in changesStream event
* 🤖 Add corresponding unit tests
---------
> 修复 hookEnable 开关配置不生效的问题
* 🐞 修改 events 中配置获取异常
* 🤖 添加对应单测

fix: hook enable

---

app/core/service/PackageManagerService.ts
app/core/service/PackageVersionFileService.ts
app/core/service/PackageVersionService.ts
test/port/controller/PackageVersionFileController/listFiles.test.ts
test/port/controller/PackageVersionFileController/raw.test.ts

closes https://github.com/cnpm/cnpmcore/issues/481

feat: use unpkg README.md to update package version readme property

---

app/core/service/PackageSearchService.ts
app/repository/PackageRepository.ts
app/repository/SearchRepository.ts
docs/elasticsearch-setup.md

> Revert ineffective changes from https://github.com/cnpm/cnpmcore/pull/581, add username index
* 🧶 Add username field to maintainers in search results, handle uniformly when writing
* 📚 Update index documentation
-----
> 回滚 https://github.com/cnpm/cnpmcore/pull/581 无效改动，添加 username 索引
* 🧶 搜索结果中的 maintainers 添加 username 字段，写入时统一处理
* 📚 更新索引文档说明

fix: author display in cli

---

package.json

https://github.com/node-modules/oss-client/pull/15

fix: use oss-cnpm@5.0.1

---

package.json

https://github.com/eggjs/egg-cors/pull/27

feat: use egg-cors@3

---

app/common/adapter/binary/GithubBinary.ts

closes https://github.com/cnpm/cnpm/issues/435

fix: github file size limit increased to 250mb

---

README.md
docs/registry-api.md

closes https://github.com/cnpm/cnpmcore/issues/630

chore: add registry api doc

---

config/binaries.ts

closes https://github.com/cnpm/cnpmcore/issues/635

feat: mirror ant-design-charts releases

---

app/common/FileUtil.ts
app/core/service/BinarySyncerService.ts

https://github.com/cnpm/cnpmcore/issues/652

fix: dont set empty string authorization header

---

Dockerfile
app/port/controller/AccessController.ts
package.json
test/cli/CliUtil.ts

https://github.com/advisories/GHSA-vx3p-948g-6vhq
https://hub.docker.com/repository/docker/fengmk2/cnpmcore/tags/v4/sha256-38b310438907eec1f00da6f110f6f24c81c85e983833fddd08a31598510154f3

fix: remove npm-cli-login for ssri security

---

app/port/controller/package/DownloadPackageVersionTar.ts
test/port/controller/package/DownloadPackageVersionTarController.test.ts

revert https://github.com/cnpm/cnpmcore/pull/763

fix: remove block tgz

---

.github/workflows/release.yml

https://github.com/node-modules/github-actions/issues/14

fix: use npm trusted publisher
